name: AdsText
main: com.acey.adstext.AdsTextPlugin
version: 1.1.2c
api-version: 1.21
author: Acey
description: A lightweight broadcast and chatbot plugin for Minecraft servers.

commands:
  ads:
    description: Reloads all plugin configs.
    usage: /ads reload
    permission: adstext.reload

permissions:
  adstext.reload:
    description: Allows use of /ads reload
    default: op
